FROM opensearchproject/opensearch:latest

ENV cluster.name=opensearch-cluster \
    node.name=opensearch-node1 \
    discovery.seed_hosts=opensearch-node1 \
    cluster.initial_cluster_manager_nodes=opensearch-node1 \
    bootstrap.memory_lock=true \
    DISABLE_SECURITY_PLUGIN=true \
    OPENSEARCH_JAVA_OPTS="-Xms256m -Xmx256m"
    
EXPOSE 9200

COPY opensearch.yml /usr/share/opensearch/config/opensearch.yml

ENTRYPOINT ["/usr/share/opensearch/bin/opensearch"]